### PR TITLE
support for json configuration

### PR DESCRIPTION
**Pull request by artiomponkratov**

### CODE REVIEW

**Comment by SeppPenner** [comment]
I will check this tomorrow (I hope at least).

**Comment by artiomponkratov** [comment]
> 
> 
> I will check this tomorrow (I hope at least).

Hi, could you please check the pull request today?

**Comment by artiomponkratov** [comment]
@SeppPenner Could you also push a new package to nuget ?

**Comment by SeppPenner** [comment]
@artiomponkratov I've already merged your pull request and will create a new nuget package today. I was a bit busy before, but now I will take a look at it in detail :) I will give you a short update here once the package is available.

**Comment by SeppPenner** [comment]
Nice idea with the `SqlTypeHelper` class. I have just adjusted the code style and documentation a bit, but the rest looks really good :)

**Comment by SeppPenner** [comment]
So, the NuGet package will be available soon (Within the next hour) :) Just tell me if you find anything else in the package. One more thing: I have adjusted your `Id` field from `"Id": "IdAutoincrement",` to `"Id": "IdAutoIncrement",`. After changing this in your configuration, it should work as expected. If not, please tell me. And thank you for your time and this pull request.

**Comment by SeppPenner** [comment]
And another thing just to mention it: You had the `;` char in the wrong position in the documentation for the database connection string (But I guess that was just a copy paste error). :)

**Pull request merged**
